# Copyright (c) 2022-2024, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Common functions that can be used to enable different events.

Events include anything related to altering the simulation state. This includes changing the physics
materials, applying external forces, and resetting the state of the asset.

The functions can be passed to the :class:`omni.isaac.lab.managers.EventTermCfg` object to enable
the event introduced by the function.
"""

from __future__ import annotations

import torch
import warnings
from typing import TYPE_CHECKING, Literal

import carb
import omni.physics.tensors.impl.api as physx

import omni.isaac.lab.sim as sim_utils
import omni.isaac.lab.utils.math as math_utils
from omni.isaac.lab.actuators import ImplicitActuator
from omni.isaac.lab.assets import Articulation, RigidObject
from omni.isaac.lab.managers import SceneEntityCfg
from omni.isaac.lab.terrains import TerrainImporter

from omni.isaac.lab.sim import schemas
import omni.isaac.core.utils.prims as prim_utils
from pxr import UsdPhysics
import omni.isaac.lab.sim as sim_utils
import omni.isaac.lab.sim.schemas as schemas

from omni.isaac.lab.managers.manager_base import ManagerTermBase
from omni.isaac.lab.managers import EventTermCfg

if TYPE_CHECKING:
    from omni.isaac.lab.envs import ManagerBasedEnv, ManagerBasedRLEnv


def randomize_rigid_body_material(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    static_friction_range: tuple[float, float],
    dynamic_friction_range: tuple[float, float],
    restitution_range: tuple[float, float],
    num_buckets: int,
    asset_cfg: SceneEntityCfg,
):
    """Randomize the physics materials on all geometries of the asset.

    This function creates a set of physics materials with random static friction, dynamic friction, and restitution
    values. The number of materials is specified by ``num_buckets``. The materials are generated by sampling
    uniform random values from the given ranges.

    The material properties are then assigned to the geometries of the asset. The assignment is done by
    creating a random integer tensor of shape  (num_instances, max_num_shapes) where ``num_instances``
    is the number of assets spawned and ``max_num_shapes`` is the maximum number of shapes in the asset (over
    all bodies). The integer values are used as indices to select the material properties from the
    material buckets.

    .. attention::
        This function uses CPU tensors to assign the material properties. It is recommended to use this function
        only during the initialization of the environment. Otherwise, it may lead to a significant performance
        overhead.

    .. note::
        PhysX only allows 64000 unique physics materials in the scene. If the number of materials exceeds this
        limit, the simulation will crash.
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]

    if not isinstance(asset, (RigidObject, Articulation)):
        raise ValueError(
            f"Randomization term 'randomize_rigid_body_material' not supported for asset: '{asset_cfg.name}'"
            f" with type: '{type(asset)}'."
        )

    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device="cpu")
    else:
        env_ids = env_ids.cpu()

    # retrieve material buffer
    materials = asset.root_physx_view.get_material_properties()

    # sample material properties from the given ranges
    material_samples = torch.zeros(materials[env_ids].shape)
    material_samples[..., 0].uniform_(*static_friction_range)
    material_samples[..., 1].uniform_(*dynamic_friction_range)
    material_samples[..., 2].uniform_(*restitution_range)

    # create uniform range tensor for bucketing
    lo = torch.tensor([static_friction_range[0], dynamic_friction_range[0], restitution_range[0]], device="cpu")
    hi = torch.tensor([static_friction_range[1], dynamic_friction_range[1], restitution_range[1]], device="cpu")

    # to avoid 64k material limit in physx, we bucket materials by binning randomized material properties
    # into buckets based on the number of buckets specified
    for d in range(3):
        buckets = torch.tensor([(hi[d] - lo[d]) * i / num_buckets + lo[d] for i in range(num_buckets)], device="cpu")
        material_samples[..., d] = buckets[torch.searchsorted(buckets, material_samples[..., d].contiguous()) - 1]

    # update material buffer with new samples
    if isinstance(asset, Articulation) and asset_cfg.body_ids != slice(None):
        # obtain number of shapes per body (needed for indexing the material properties correctly)
        # note: this is a workaround since the Articulation does not provide a direct way to obtain the number of shapes
        #  per body. We use the physics simulation view to obtain the number of shapes per body.
        num_shapes_per_body = []
        for link_path in asset.root_physx_view.link_paths[0]:
            link_physx_view = asset._physics_sim_view.create_rigid_body_view(link_path)  # type: ignore
            num_shapes_per_body.append(link_physx_view.max_shapes)

        # sample material properties from the given ranges
        for body_id in asset_cfg.body_ids:
            # start index of shape
            start_idx = sum(num_shapes_per_body[:body_id])
            # end index of shape
            end_idx = start_idx + num_shapes_per_body[body_id]
            # assign the new materials
            # material ids are of shape: num_env_ids x num_shapes
            # material_buckets are of shape: num_buckets x 3
            materials[env_ids, start_idx:end_idx] = material_samples[:, start_idx:end_idx]
    else:
        materials[env_ids] = material_samples

    # apply to simulation
    asset.root_physx_view.set_material_properties(materials, env_ids)


def add_body_mass(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    mass_distribution_params: tuple[float, float],
    asset_cfg: SceneEntityCfg,
):
    """Randomize the mass of the bodies by adding a random value sampled from the given range.

    .. tip::
        This function uses CPU tensors to assign the body masses. It is recommended to use this function
        only during the initialization of the environment.

    .. deprecated:: v0.4
        This function is deprecated. Please use :func:`randomize_rigid_body_mass` with ``operation="add"`` instead.

    """
    msg = "Event term 'add_body_mass' is deprecated. Please use 'randomize_rigid_body_mass' with operation='add'."
    warnings.warn(msg, DeprecationWarning)
    carb.log_warn(msg)

    # call the new function
    randomize_rigid_body_mass(
        env, env_ids, asset_cfg, mass_distribution_params, operation="add", distribution="uniform"
    )


def randomize_rigid_body_mass(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    asset_cfg: SceneEntityCfg,
    mass_distribution_params: tuple[float, float],
    operation: Literal["add", "scale", "abs"],
    distribution: Literal["uniform", "log_uniform", "gaussian"] = "uniform",
):
    """Randomize the mass of the bodies by adding, scaling, or setting random values.

    This function allows randomizing the mass of the bodies of the asset. The function samples random values from the
    given distribution parameters and adds, scales, or sets the values into the physics simulation based on the operation.

    .. tip::
        This function uses CPU tensors to assign the body masses. It is recommended to use this function
        only during the initialization of the environment.
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]

    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device="cpu")
    else:
        env_ids = env_ids.cpu()

    # resolve body indices
    if asset_cfg.body_ids == slice(None):
        body_ids = torch.arange(asset.num_bodies, dtype=torch.int, device="cpu")
    else:
        body_ids = torch.tensor(asset_cfg.body_ids, dtype=torch.int, device="cpu")

    # get the current masses of the bodies (num_assets, num_bodies)
    masses = asset.root_physx_view.get_masses()
    # apply randomization on default values
    masses[env_ids[:, None], body_ids] = asset.data.default_mass[env_ids[:, None], body_ids].clone()

    # sample from the given range
    # note: we modify the masses in-place for all environments
    #   however, the setter takes care that only the masses of the specified environments are modified
    masses = _randomize_prop_by_op(
        masses, mass_distribution_params, env_ids, body_ids, operation=operation, distribution=distribution
    )

    # set the mass into the physics simulation
    asset.root_physx_view.set_masses(masses, env_ids)


def randomize_physics_scene_gravity(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    gravity_distribution_params: tuple[list[float], list[float]],
    operation: Literal["add", "scale", "abs"],
    distribution: Literal["uniform", "log_uniform", "gaussian"] = "uniform",
):
    """Randomize gravity by adding, scaling, or setting random values.

    This function allows randomizing gravity of the physics scene. The function samples random values from the
    given distribution parameters and adds, scales, or sets the values into the physics simulation based on the
    operation.

    The distribution parameters are lists of two elements each, representing the lower and upper bounds of the
    distribution for the x, y, and z components of the gravity vector. The function samples random values for each
    component independently.

    .. attention::
        This function applied the same gravity for all the environments.

    .. tip::
        This function uses CPU tensors to assign gravity.
    """
    # get the current gravity
    gravity = torch.tensor(env.sim.cfg.gravity, device="cpu").unsqueeze(0)
    dist_param_0 = torch.tensor(gravity_distribution_params[0], device="cpu")
    dist_param_1 = torch.tensor(gravity_distribution_params[1], device="cpu")
    gravity = _randomize_prop_by_op(
        gravity,
        (dist_param_0, dist_param_1),
        None,
        slice(None),
        operation=operation,
        distribution=distribution,
    )
    # unbatch the gravity tensor into a list
    gravity = gravity[0].tolist()

    # set the gravity into the physics simulation
    physics_sim_view: physx.SimulationView = sim_utils.SimulationContext.instance().physics_sim_view
    physics_sim_view.set_gravity(carb.Float3(*gravity))


def randomize_actuator_gains(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    asset_cfg: SceneEntityCfg,
    stiffness_distribution_params: tuple[float, float] | None = None,
    damping_distribution_params: tuple[float, float] | None = None,
    operation: Literal["add", "scale", "abs"] = "abs",
    distribution: Literal["uniform", "log_uniform", "gaussian"] = "uniform",
):
    """Randomize the actuator gains in an articulation by adding, scaling, or setting random values.

    This function allows randomizing the actuator stiffness and damping gains.

    The function samples random values from the given distribution parameters and applies the operation to the joint properties.
    It then sets the values into the actuator models. If the distribution parameters are not provided for a particular property,
    the function does not modify the property.

    .. tip::
        For implicit actuators, this function uses CPU tensors to assign the actuator gains into the simulation.
        In such cases, it is recommended to use this function only during the initialization of the environment.

    Raises:
        NotImplementedError: If the joint indices are in explicit motor mode. This operation is currently
            not supported for explicit actuator models.
    """
    # extract the used quantities (to enable type-hinting)
    asset: Articulation = env.scene[asset_cfg.name]

    # construct an array of prim_paths with the environment ids
    if env_ids is not None:
        # add joints to prim_paths
        prim_paths = [f"/World/envs/env_{env_id}/Robot/base_link/base_roll_joint" for env_id in env_ids]
        prim_paths += [f"/World/envs/env_{env_id}/Robot/base_roll_link/base_r_drive_wheel_joint" for env_id in env_ids]
        prim_paths += [f"/World/envs/env_{env_id}/Robot/base_roll_link/base_l_drive_wheel_joint" for env_id in env_ids]
    else:
        # add joints to prim_paths
        prim_paths = [f"/World/envs/env_{env_id}/Robot/base_link/base_roll_joint" for env_id in range(env.scene.num_envs)]
        prim_paths += [f"/World/envs/env_{env_id}/Robot/base_roll_link/base_r_drive_wheel_joint" for env_id in range(env.scene.num_envs)]
        prim_paths += [f"/World/envs/env_{env_id}/Robot/base_roll_link/base_l_drive_wheel_joint" for env_id in range(env.scene.num_envs)]
        
    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device=asset.device)

    # resolve joint indices
    if asset_cfg.joint_ids == slice(None):
        joint_ids_list = range(asset.num_joints)
        joint_ids = slice(None)  # for optimization purposes
    else:
        joint_ids_list = asset_cfg.joint_ids
        joint_ids = torch.tensor(asset_cfg.joint_ids, dtype=torch.int, device=asset.device)

    # check if none of the joint indices are in explicit motor mode
    for joint_index in joint_ids_list:
        for act_name, actuator in asset.actuators.items():
            # if joint indices are a slice (i.e., all joints are captured) or the joint index is in the actuator
            if actuator.joint_indices == slice(None) or joint_index in actuator.joint_indices:
                if not isinstance(actuator, ImplicitActuator):
                    raise NotImplementedError(
                        "Event term 'randomize_actuator_stiffness_and_damping' is performed on asset"
                        f" '{asset_cfg.name}' on the joint '{asset.joint_names[joint_index]}' ('{joint_index}') which"
                        f" uses an explicit actuator model '{act_name}<{actuator.__class__.__name__}>'. This operation"
                        " is currently not supported for explicit actuator models."
                    )

    # sample joint properties from the given ranges and set into the physics simulation
    # -- stiffness
    if stiffness_distribution_params is not None:
        stiffness = asset.data.default_joint_stiffness.to(asset.device).clone()
        stiffness = _randomize_prop_by_op(
            stiffness, stiffness_distribution_params, env_ids, joint_ids, operation=operation, distribution=distribution
        )[env_ids][:, joint_ids]
        asset.write_joint_stiffness_to_sim(stiffness, joint_ids=joint_ids, env_ids=env_ids)
    # -- damping
    if damping_distribution_params is not None:
        damping = asset.data.default_joint_damping.to(asset.device).clone()
        damping = _randomize_prop_by_op(
            damping, damping_distribution_params, env_ids, joint_ids, operation=operation, distribution=distribution
        )[env_ids][:, joint_ids]
        asset.write_joint_damping_to_sim(damping, joint_ids=joint_ids, env_ids=env_ids)
    
    for prim_path in prim_paths:
        cfg = sim_utils.JointDrivePropertiesCfg(drive_type="acceleration")
        schemas.modify_joint_drive_properties(prim_path, cfg)
        cfg = sim_utils.JointDrivePropertiesCfg(drive_type="force")
        schemas.modify_joint_drive_properties(prim_path, cfg)
        
    for prim_path in prim_paths:
        cfg = sim_utils.JointDrivePropertiesCfg(drive_type="force")
        _validate_joint_drive_properties_on_prim(prim_path, cfg)


def _validate_joint_drive_properties_on_prim(prim_path: str, cfg: schemas.JointDrivePropertiesCfg, verbose: bool = False):
        """Validate the mass properties on the prim.

        Note:
            Right now this function exploits the hierarchy in the asset to check the properties. This is not a
            fool-proof way of checking the properties.
        """
        joint_cfg = cfg
        # the root prim
        root_prim = prim_utils.get_prim_at_path(prim_path)
        # check joint drive properties are set correctly
        for link_prim in root_prim.GetAllChildren():
            for joint_prim in link_prim.GetChildren():
                if joint_prim.IsA(UsdPhysics.PrismaticJoint) or joint_prim.IsA(UsdPhysics.RevoluteJoint):
                    # check it has drive API
                    if not joint_prim.HasAPI(UsdPhysics.DriveAPI):
                        raise ValueError(f"Joint prim {joint_prim.GetPrimPath()} does not have drive api.")
                    # iterate over the joint properties
                    for attr_name, attr_value in joint_cfg.__dict__.items():
                        # skip names we know are not present
                        if attr_name == "func":
                            continue
                        # manually check joint type
                        if attr_name == "drive_type":
                            if joint_prim.IsA(UsdPhysics.PrismaticJoint):
                                prim_attr_name = "drive:linear:physics:type"
                            elif joint_prim.IsA(UsdPhysics.RevoluteJoint):
                                prim_attr_name = "drive:angular:physics:type"
                            else:
                                raise ValueError(f"Unknown joint type for prim {joint_prim.GetPrimPath()}")
                            # check the value
                            if not attr_value == joint_prim.GetAttribute(prim_attr_name).Get():
                                raise ValueError(f"Joint prim {joint_prim.GetPrimPath()} has incorrect drive type.")
                            continue
                elif verbose:
                    print(f"Skipping prim {joint_prim.GetPrimPath()} as it is not a joint drive api.")

def reset_joint_drive_type(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
):
    
    # construct an array of prim_paths with the environment ids
    if env_ids is not None:
        prim_paths = [f"/World/envs/env_{env_id}/Robot" for env_id in env_ids]
    else:
        prim_paths = [f"/World/envs/env_{env_id}/Robot" for env_id in range(env.scene.num_envs)]
    
    for prim_path in prim_paths:
        cfg = sim_utils.JointDrivePropertiesCfg(drive_type="acceleration")
        schemas.modify_joint_drive_properties(prim_path, cfg)
        cfg = sim_utils.JointDrivePropertiesCfg(drive_type="force")
        schemas.modify_joint_drive_properties(prim_path, cfg)
        
    for prim_path in prim_paths:
        cfg = sim_utils.JointDrivePropertiesCfg(drive_type="force")
        _validate_joint_drive_properties_on_prim(prim_path, cfg)
    
    

def reset_joint_effort_limits(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    asset_cfg: SceneEntityCfg,
    effort_limit_params: tuple[float, float] | None = None,
    operation: Literal["add", "scale", "abs"] = "abs",
    distribution: Literal["uniform", "log_uniform", "gaussian"] = "uniform",
):

    # extract the used quantities (to enable type-hinting)
    asset: Articulation = env.scene[asset_cfg.name]

    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device=asset.device)

    # resolve joint indices
    if asset_cfg.joint_ids == slice(None):
        joint_ids_list = range(asset.num_joints)
        joint_ids = slice(None)  # for optimization purposes
    else:
        joint_ids_list = asset_cfg.joint_ids
        joint_ids = torch.tensor(asset_cfg.joint_ids, dtype=torch.int, device=asset.device)

    # check if none of the joint indices are in explicit motor mode
    for joint_index in joint_ids_list:
        for act_name, actuator in asset.actuators.items():
            # if joint indices are a slice (i.e., all joints are captured) or the joint index is in the actuator
            if actuator.joint_indices == slice(None) or joint_index in actuator.joint_indices:
                if not isinstance(actuator, ImplicitActuator):
                    raise NotImplementedError(
                        "Event term 'randomize_actuator_stiffness_and_damping' is performed on asset"
                        f" '{asset_cfg.name}' on the joint '{asset.joint_names[joint_index]}' ('{joint_index}') which"
                        f" uses an explicit actuator model '{act_name}<{actuator.__class__.__name__}>'. This operation"
                        " is currently not supported for explicit actuator models."
                    )

    usd_effort_limit = asset.root_physx_view.get_dof_max_forces().clone().to(asset.device)

    # sample joint properties from the given ranges and set into the physics simulation
    # -- effort limits
    if effort_limit_params is not None:
        effort_limits = usd_effort_limit[:, joint_ids]
        effort_limits = _randomize_prop_by_op(
            effort_limits, effort_limit_params, env_ids, joint_ids, operation=operation, distribution=distribution
        )[env_ids][:, joint_ids]
        asset.write_joint_effort_limit_to_sim(effort_limits, joint_ids=joint_ids, env_ids=env_ids)
        

def randomize_joint_parameters(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    asset_cfg: SceneEntityCfg,
    friction_distribution_params: tuple[float, float] | None = None,
    armature_distribution_params: tuple[float, float] | None = None,
    lower_limit_distribution_params: tuple[float, float] | None = None,
    upper_limit_distribution_params: tuple[float, float] | None = None,
    operation: Literal["add", "scale", "abs"] = "abs",
    distribution: Literal["uniform", "log_uniform", "gaussian"] = "uniform",
):
    """Randomize the joint parameters of an articulation by adding, scaling, or setting random values.

    This function allows randomizing the joint parameters of the asset.
    These correspond to the physics engine joint properties that affect the joint behavior.

    The function samples random values from the given distribution parameters and applies the operation to the joint properties.
    It then sets the values into the physics simulation. If the distribution parameters are not provided for a
    particular property, the function does not modify the property.

    .. tip::
        This function uses CPU tensors to assign the joint properties. It is recommended to use this function
        only during the initialization of the environment.
    """
    # extract the used quantities (to enable type-hinting)
    asset: Articulation = env.scene[asset_cfg.name]

    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device=asset.device)

    # resolve joint indices
    if asset_cfg.joint_ids == slice(None):
        joint_ids = slice(None)  # for optimization purposes
    else:
        joint_ids = torch.tensor(asset_cfg.joint_ids, dtype=torch.int, device=asset.device)

    # sample joint properties from the given ranges and set into the physics simulation
    # -- friction
    if friction_distribution_params is not None:
        friction = asset.data.default_joint_friction.to(asset.device).clone()
        friction = _randomize_prop_by_op(
            friction, friction_distribution_params, env_ids, joint_ids, operation=operation, distribution=distribution
        )[env_ids][:, joint_ids]
        asset.write_joint_friction_to_sim(friction, joint_ids=joint_ids, env_ids=env_ids)
    # -- armature
    if armature_distribution_params is not None:
        armature = asset.data.default_joint_armature.to(asset.device).clone()
        armature = _randomize_prop_by_op(
            armature, armature_distribution_params, env_ids, joint_ids, operation=operation, distribution=distribution
        )[env_ids][:, joint_ids]
        asset.write_joint_armature_to_sim(armature, joint_ids=joint_ids, env_ids=env_ids)
    # -- dof limits
    if lower_limit_distribution_params is not None or upper_limit_distribution_params is not None:
        dof_limits = asset.data.default_joint_limits.to(asset.device).clone()
        if lower_limit_distribution_params is not None:
            lower_limits = dof_limits[..., 0]
            lower_limits = _randomize_prop_by_op(
                lower_limits,
                lower_limit_distribution_params,
                env_ids,
                joint_ids,
                operation=operation,
                distribution=distribution,
            )[env_ids][:, joint_ids]
            dof_limits[env_ids[:, None], joint_ids, 0] = lower_limits
        if upper_limit_distribution_params is not None:
            upper_limits = dof_limits[..., 1]
            upper_limits = _randomize_prop_by_op(
                upper_limits,
                upper_limit_distribution_params,
                env_ids,
                joint_ids,
                operation=operation,
                distribution=distribution,
            )[env_ids][:, joint_ids]
            dof_limits[env_ids[:, None], joint_ids, 1] = upper_limits
        if (dof_limits[env_ids[:, None], joint_ids, 0] > dof_limits[env_ids[:, None], joint_ids, 1]).any():
            raise ValueError(
                "Randomization term 'randomize_joint_parameters' is setting lower joint limits that are greater than"
                " upper joint limits."
            )

        asset.write_joint_limits_to_sim(dof_limits[env_ids][:, joint_ids], joint_ids=joint_ids, env_ids=env_ids)


def randomize_fixed_tendon_parameters(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor | None,
    asset_cfg: SceneEntityCfg,
    stiffness_distribution_params: tuple[float, float] | None = None,
    damping_distribution_params: tuple[float, float] | None = None,
    limit_stiffness_distribution_params: tuple[float, float] | None = None,
    lower_limit_distribution_params: tuple[float, float] | None = None,
    upper_limit_distribution_params: tuple[float, float] | None = None,
    rest_length_distribution_params: tuple[float, float] | None = None,
    offset_distribution_params: tuple[float, float] | None = None,
    operation: Literal["add", "scale", "abs"] = "abs",
    distribution: Literal["uniform", "log_uniform", "gaussian"] = "uniform",
):
    """Randomize the fixed tendon parameters of an articulation by adding, scaling, or setting random values.

    This function allows randomizing the fixed tendon parameters of the asset.
    These correspond to the physics engine tendon properties that affect the joint behavior.

    The function samples random values from the given distribution parameters and applies the operation to the tendon properties.
    It then sets the values into the physics simulation. If the distribution parameters are not provided for a
    particular property, the function does not modify the property.

    """
    # extract the used quantities (to enable type-hinting)
    asset: Articulation = env.scene[asset_cfg.name]

    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device=asset.device)

    # resolve joint indices
    if asset_cfg.fixed_tendon_ids == slice(None):
        fixed_tendon_ids = slice(None)  # for optimization purposes
    else:
        fixed_tendon_ids = torch.tensor(asset_cfg.fixed_tendon_ids, dtype=torch.int, device=asset.device)

    # sample tendon properties from the given ranges and set into the physics simulation
    # -- stiffness
    if stiffness_distribution_params is not None:
        stiffness = asset.data.default_fixed_tendon_stiffness.clone()
        stiffness = _randomize_prop_by_op(
            stiffness,
            stiffness_distribution_params,
            env_ids,
            fixed_tendon_ids,
            operation=operation,
            distribution=distribution,
        )[env_ids][:, fixed_tendon_ids]
        asset.set_fixed_tendon_stiffness(stiffness, fixed_tendon_ids, env_ids)
    # -- damping
    if damping_distribution_params is not None:
        damping = asset.data.default_fixed_tendon_damping.clone()
        damping = _randomize_prop_by_op(
            damping,
            damping_distribution_params,
            env_ids,
            fixed_tendon_ids,
            operation=operation,
            distribution=distribution,
        )[env_ids][:, fixed_tendon_ids]
        asset.set_fixed_tendon_damping(damping, fixed_tendon_ids, env_ids)
    # -- limit stiffness
    if limit_stiffness_distribution_params is not None:
        limit_stiffness = asset.data.default_fixed_tendon_limit_stiffness.clone()
        limit_stiffness = _randomize_prop_by_op(
            limit_stiffness,
            limit_stiffness_distribution_params,
            env_ids,
            fixed_tendon_ids,
            operation=operation,
            distribution=distribution,
        )[env_ids][:, fixed_tendon_ids]
        asset.set_fixed_tendon_limit_stiffness(limit_stiffness, fixed_tendon_ids, env_ids)
    # -- limits
    if lower_limit_distribution_params is not None or upper_limit_distribution_params is not None:
        limit = asset.data.default_fixed_tendon_limit.clone()
        # -- lower limit
        if lower_limit_distribution_params is not None:
            lower_limit = limit[..., 0]
            lower_limit = _randomize_prop_by_op(
                lower_limit,
                lower_limit_distribution_params,
                env_ids,
                fixed_tendon_ids,
                operation=operation,
                distribution=distribution,
            )[env_ids][:, fixed_tendon_ids]
            limit[env_ids[:, None], fixed_tendon_ids, 0] = lower_limit
        # -- upper limit
        if upper_limit_distribution_params is not None:
            upper_limit = limit[..., 1]
            upper_limit = _randomize_prop_by_op(
                upper_limit,
                upper_limit_distribution_params,
                env_ids,
                fixed_tendon_ids,
                operation=operation,
                distribution=distribution,
            )[env_ids][:, fixed_tendon_ids]
            limit[env_ids[:, None], fixed_tendon_ids, 1] = upper_limit
        if (limit[env_ids[:, None], fixed_tendon_ids, 0] > limit[env_ids[:, None], fixed_tendon_ids, 1]).any():
            raise ValueError(
                "Randomization term 'randomize_fixed_tendon_parameters' is setting lower tendon limits that are greater"
                " than upper tendon limits."
            )
        asset.set_fixed_tendon_limit(limit, fixed_tendon_ids, env_ids)
    # -- rest length
    if rest_length_distribution_params is not None:
        rest_length = asset.data.default_fixed_tendon_rest_length.clone()
        rest_length = _randomize_prop_by_op(
            rest_length,
            rest_length_distribution_params,
            env_ids,
            fixed_tendon_ids,
            operation=operation,
            distribution=distribution,
        )[env_ids][:, fixed_tendon_ids]
        asset.set_fixed_tendon_rest_length(rest_length, fixed_tendon_ids, env_ids)
    # -- offset
    if offset_distribution_params is not None:
        offset = asset.data.default_fixed_tendon_offset.clone()
        offset = _randomize_prop_by_op(
            offset,
            offset_distribution_params,
            env_ids,
            fixed_tendon_ids,
            operation=operation,
            distribution=distribution,
        )[env_ids][:, fixed_tendon_ids]
        asset.set_fixed_tendon_offset(offset, fixed_tendon_ids, env_ids)

    asset.write_fixed_tendon_properties_to_sim(fixed_tendon_ids, env_ids)


def apply_external_force_torque(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    force_range: tuple[float, float],
    torque_range: tuple[float, float],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Randomize the external forces and torques applied to the bodies.

    This function creates a set of random forces and torques sampled from the given ranges. The number of forces
    and torques is equal to the number of bodies times the number of environments. The forces and torques are
    applied to the bodies by calling ``asset.set_external_force_and_torque``. The forces and torques are only
    applied when ``asset.write_data_to_sim()`` is called in the environment.
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]
    # resolve environment ids
    if env_ids is None:
        env_ids = torch.arange(env.scene.num_envs, device=asset.device)
    # resolve number of bodies
    num_bodies = len(asset_cfg.body_ids) if isinstance(asset_cfg.body_ids, list) else asset.num_bodies

    # sample random forces and torques
    size = (len(env_ids), num_bodies, 3)
    forces = math_utils.sample_uniform(*force_range, size, asset.device)
    torques = math_utils.sample_uniform(*torque_range, size, asset.device)
    # set the forces and torques into the buffers
    # note: these are only applied when you call: `asset.write_data_to_sim()`
    asset.set_external_force_and_torque(forces, torques, env_ids=env_ids, body_ids=asset_cfg.body_ids)


def push_by_setting_velocity(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    velocity_range: dict[str, tuple[float, float]],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Push the asset by setting the root velocity to a random value within the given ranges.

    This creates an effect similar to pushing the asset with a random impulse that changes the asset's velocity.
    It samples the root velocity from the given ranges and sets the velocity into the physics simulation.

    The function takes a dictionary of velocity ranges for each axis and rotation. The keys of the dictionary
    are ``x``, ``y``, ``z``, ``roll``, ``pitch``, and ``yaw``. The values are tuples of the form ``(min, max)``.
    If the dictionary does not contain a key, the velocity is set to zero for that axis.
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]

    # velocities
    vel_w = asset.data.root_vel_w[env_ids]
    # sample random velocities
    range_list = [velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
    ranges = torch.tensor(range_list, device=asset.device)
    vel_w[:] = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], vel_w.shape, device=asset.device)
    # set the velocities into the physics simulation
    asset.write_root_velocity_to_sim(vel_w, env_ids=env_ids)

def reset_root_state_ee_tcp(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    pose_range: dict[str, tuple[float, float]],
    velocity_range: dict[str, tuple[float, float]],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
    object_cfg: SceneEntityCfg = SceneEntityCfg("test_object"),
):
    """Reset the asset root state
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]
    test_object: RigidObject | Articulation = env.scene[object_cfg.name]
    # get default root state
    root_states = test_object.data.default_root_state[env_ids].clone()
    ee_tcp_body_id = asset.find_bodies("ee_tcp")[0]
    ee_tcp_pos_w = asset.data.body_pos_w[env_ids, ee_tcp_body_id, :].squeeze(1)
    
    # TODO: Add an offset in z in the ee_tcp frame
    
    ee_tcp_quat_w = asset.data.body_quat_w[env_ids, ee_tcp_body_id, :].squeeze(1)
    block_offset = torch.zeros([2, 3], device=root_states.device)
    block_offset[0, 0] = 0.1579#  + 0.3
    block_offset[0, 1] = -2.4219
    block_offset[0, 2] = 0.95
    block_offset[1, 0] = 0.1579# + 0.3
    block_offset[1, 1] = 2.5779
    block_offset[1, 2] = 0.95
            
    # block_offset = math_utils.quat_apply(ee_tcp_quat_w, block_offset)

    positions = block_offset[env_ids] # ee_tcp_pos_w + block_offset

    # set into the physics simulation
    test_object.write_root_pose_to_sim(torch.cat([positions, root_states[:, 3:7]], dim=-1), env_ids=env_ids)
    test_object.write_root_velocity_to_sim(root_states[:, 7:13], env_ids=env_ids)

def reset_root_state_uniform(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    pose_range: dict[str, tuple[float, float]],
    velocity_range: dict[str, tuple[float, float]],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Reset the asset root state to a random position and velocity uniformly within the given ranges.

    This function randomizes the root position and velocity of the asset.

    * It samples the root position from the given ranges and adds them to the default root position, before setting
      them into the physics simulation.
    * It samples the root orientation from the given ranges and sets them into the physics simulation.
    * It samples the root velocity from the given ranges and sets them into the physics simulation.

    The function takes a dictionary of pose and velocity ranges for each axis and rotation. The keys of the
    dictionary are ``x``, ``y``, ``z``, ``roll``, ``pitch``, and ``yaw``. The values are tuples of the form
    ``(min, max)``. If the dictionary does not contain a key, the position or velocity is set to zero for that axis.
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]
    # get default root state
    root_states = asset.data.default_root_state[env_ids].clone()

    # poses
    range_list = [pose_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
    ranges = torch.tensor(range_list, device=asset.device)
    rand_samples = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=asset.device)

    positions = root_states[:, 0:3] + env.scene.env_origins[env_ids] + rand_samples[:, 0:3]
    orientations_delta = math_utils.quat_from_euler_xyz(rand_samples[:, 3], rand_samples[:, 4], rand_samples[:, 5])
    orientations = math_utils.quat_mul(root_states[:, 3:7], orientations_delta)
    # velocities
    range_list = [velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
    ranges = torch.tensor(range_list, device=asset.device)
    rand_samples = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=asset.device)

    velocities = root_states[:, 7:13] + rand_samples

    # set into the physics simulation
    asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
    asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)
    
class reset_root_state_uniform_per_env(ManagerTermBase):
    """Reset the asset root state to a random position and velocity uniformly within the given ranges.
    
    This function does the same as `reset_root_state_uniform`, but it resets the root state for each environment 
    independently by storing ranges for each environment. This is for curriculum learning where the ranges for each
    environment can be different due to level progression.
    
    Currently not that general, and setup for use in LiftCube task.
    """
    
    current_ranges: torch.tensor
    
    def __init__(self, cfg: EventTermCfg, env: ManagerBasedEnv):
        super().__init__(cfg, env)
        self._initialised = False
        self.initial_root_state = None
        self.current_levels = torch.zeros(env.num_envs, device=env.device)
        self.current_ranges = torch.zeros(env.num_envs, 6, 2, device=env.device)
        self.level_intervals = 1
    
    def __call__(self, 
                env: ManagerBasedEnv, 
                env_ids: torch.Tensor,
                initial_root_state: dict[str, tuple[float, float]],
                initial_velocity_range: dict[str, tuple[float, float]],
                x_pose_range: tuple[float, float],
                asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
                initial_level_zero: bool = True,
                ):
        
        if not self._initialised:
            self.initial_root_state = torch.tensor([initial_root_state.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]], device=env.device)
            self.vel_range_list = torch.tensor([initial_velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]], device=env.device)
            self.distance_diff = (x_pose_range[1] - x_pose_range[0]) / self.level_intervals
            self.current_ranges[:] = self.initial_root_state
            if not initial_level_zero:
                self.current_levels[:] = 1.0
        
        # extract the used quantities (to enable type-hinting)
        asset: RigidObject | Articulation = env.scene[asset_cfg.name]
        # get default root state
        root_states = asset.data.default_root_state[env_ids].clone()

        # for envs on level zero, set the sample range to self.initial_root_state
        zero_level_env_mask = self.current_levels[env_ids] == 0
        if torch.any(zero_level_env_mask):
            update_env_ids = env_ids[zero_level_env_mask]
            self.current_ranges[update_env_ids] = self.initial_root_state
        
        # for envs not on level zero, calculate the new ranges
        if torch.any(~zero_level_env_mask):
            
            # compute step size for level progression
            x_upper = x_pose_range[0] + self.current_levels[env_ids][~zero_level_env_mask] * self.distance_diff
            x_lower = x_pose_range[0]
            update_env_ids = env_ids[~zero_level_env_mask]
            self.current_ranges[update_env_ids, 0, 0] = x_lower
            self.current_ranges[update_env_ids, 0, 1] = x_upper 

        # poses
        # self.current_ranges = torch.tensor(range_list, device=asset.device)
        rand_samples = math_utils.sample_uniform(self.current_ranges[env_ids, :, 0], self.current_ranges[env_ids, :, 1], (len(env_ids), 6), device=asset.device)

        positions = root_states[:, 0:3] + env.scene.env_origins[env_ids] + rand_samples[:, 0:3]
        orientations_delta = math_utils.quat_from_euler_xyz(rand_samples[:, 3], rand_samples[:, 4], rand_samples[:, 5])
        orientations = math_utils.quat_mul(root_states[:, 3:7], orientations_delta)
        # velocities
        # self.current_ranges = torch.tensor(range_list, device=asset.device)
        rand_samples = math_utils.sample_uniform(self.vel_range_list[:, 0], self.vel_range_list[:, 1], (len(env_ids), 6), device=asset.device)
        velocities = root_states[:, 7:13] + rand_samples

        # set into the physics simulation
        asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
        asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)

class reset_root_state_uniform_set_height_per_env(ManagerTermBase):
    """Reset the asset root state to a random position uniformly within the given ranges.
    
    This function randomizes the root position of the asset, with a given height, and tracks ranges for each environment.
    
    Currently not that general, and setup for use in LiftCube task. Currently only supports random sampling of x and y.
    """
    
    current_ranges: torch.tensor
    
    def __init__(self, cfg: EventTermCfg, env: ManagerBasedEnv):
        super().__init__(cfg, env)
        self._initialised = False
        self.initial_root_state = None
        self.current_levels = torch.zeros(env.num_envs, device=env.device)
        self.current_position_ranges = torch.zeros(env.num_envs, 2, 2, device=env.device)
        self.level_intervals = 1
        
    def __call__(self,
                 env: ManagerBasedEnv,
                 env_ids: torch.Tensor,
                 initial_position_range: dict[str, tuple[float, float]],
                 position_range: dict[str, tuple[float, float]],
                 set_heights: list[float],
                 asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
                 initial_level_zero: bool = True,
                 ):
        
        if not self._initialised:
            self.initial_root_state = torch.tensor([initial_position_range.get(key, (0.0, 0.0)) for key in ["x", "y"]], device=env.device)
            self.position_ranges = torch.tensor([position_range.get(key, (0.0, 0.0)) for key in ["x", "y"]], device=env.device)
            self.distance_diffs = (self.position_ranges[:, 1] - self.position_ranges[:, 0]) / self.level_intervals
            self.current_position_ranges[:] = self.initial_root_state
            if not initial_level_zero:
                self.current_levels[:] = 1.0

        # extract the used quantities (to enable type-hinting)
        asset: RigidObject | Articulation = env.scene[asset_cfg.name]
        # get default root state
        root_states = asset.data.default_root_state[env_ids].clone()
        
        # for envs on level zero, set the sample range to self.initial_root_state
        zero_level_env_mask = self.current_levels[env_ids] == 0
        if torch.any(zero_level_env_mask):
            update_env_ids = env_ids[zero_level_env_mask]
            self.current_position_ranges[update_env_ids] = self.initial_root_state
            
        # for envs not on level zero, calculate the new ranges
        if torch.any(~zero_level_env_mask):
            # compute step size for level progression
            position_upper = self.current_levels[env_ids][~zero_level_env_mask].unsqueeze(-1) * self.distance_diffs + self.position_ranges[:, 0]
            position_lower = -position_upper
            update_env_ids = env_ids[~zero_level_env_mask]
            self.current_position_ranges[update_env_ids, :, 0] = position_lower
            self.current_position_ranges[update_env_ids, :, 1] = position_upper
            
        rand_samples = math_utils.sample_uniform(self.current_position_ranges[env_ids, :, 0], self.current_position_ranges[env_ids, :, 1], (len(env_ids), 2), device=asset.device)
        
        positions = root_states[:, 0:2] + env.scene.env_origins[env_ids, 0:2] + rand_samples
        set_heights_tensor = torch.tensor([set_heights[0]] * env.num_envs if len(set_heights) == 1 else set_heights, device=asset.device)
        positions = torch.cat([positions, set_heights_tensor[env_ids].unsqueeze(1)], dim=1)
        
        # set into the physics simulation
        asset.write_root_pose_to_sim(torch.cat([positions, root_states[:, 3:7]], dim=-1), env_ids=env_ids)
        asset.write_root_velocity_to_sim(torch.zeros_like(root_states[:, 7:13]), env_ids=env_ids)
        
        # update initial object position 
        masked_object_position_idx = env.observation_manager.active_terms["policy"].index("masked_object_position")
        updated_positions = positions - env.scene.env_origins[env_ids, 0:3]
        # env_ids_copy = env_ids.clone()
        env.observation_manager._group_obs_term_cfgs["policy"][masked_object_position_idx].func.reset(env_ids, updated_positions)


class reset_robot_joints_set_table_height(ManagerTermBase):
    """Class for resetting the robot joints so that the robot avoids the table.
    
    Resets all joints around the default position and velocity by the given ranges.
    
    This function samples random values from the given ranges around the default joint positions and velocities.
    The ranges are clipped to fit inside the soft joint limits. The sampled values are then set into the physics
    simulation."""
    
    table_heights: torch.tensor
    
    def __init__(self, cfg: EventTermCfg, env: ManagerBasedEnv):
        super().__init__(cfg, env)
        self.initialised = False
        self.table_heights = torch.zeros(env.num_envs, device=env.device)
        self.lift_joint_heights = torch.zeros(env.num_envs, 2, device=env.device) # arm_lift_joint and torso_lift_joint heights
        self.current_levels = torch.zeros(env.num_envs, device=env.device)
        self.position_ranges = torch.zeros(env.num_envs, 2, device=env.device)
        self.velocity_range_list = torch.zeros(env.num_envs, 2, device=env.device)
        self.lift_joint_ids = [0, 0] # [arm_lift_joint_id, torso_lift_joint_id]
        
    def __call__(self,
                 env: ManagerBasedEnv,
                 env_ids: torch.Tensor,
                 table_heights: list[float],
                 position_range: tuple[float, float],
                 velocity_range: tuple[float, float],
                 asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
                 initial_level_zero: bool = True,
    ):
        # extract the used quantities (to enable type-hinting)
        asset: Articulation = env.scene[asset_cfg.name]
        
        if not self.initialised:
            self.table_heights = torch.tensor(table_heights, device=env.device)
            self.lift_joint_heights[:, 0] = (self.table_heights - 0.1) * 2/3
            self.lift_joint_heights[:, 1] = (self.table_heights - 0.1) * 1/3
            self.lift_joint_ids[0] = asset.find_joints("arm_lift_joint")[0][0]
            self.lift_joint_ids[1] = asset.find_joints("torso_lift_joint")[0][0]
            self.initial_position_ranges = torch.tensor([position_range] * env.num_envs, device=env.device)
            self.position_ranges = torch.zeros(env.num_envs, 2, device=env.device)
            self.initial_velocity_range_list = torch.tensor([velocity_range] * env.num_envs, device=env.device)
            self.velocity_range_list = torch.zeros(env.num_envs, 2, device=env.device)
            self.initialised = True
            if not initial_level_zero:
                self.current_levels[:] = 1.0
            
        zero_level_env_mask = self.current_levels[env_ids] == 0
        if torch.any(zero_level_env_mask):
            update_env_ids = env_ids[zero_level_env_mask]
            self.position_ranges[update_env_ids] = torch.zeros(2, device=env.device)
            self.velocity_range_list[update_env_ids] = torch.zeros(2, device=env.device)
            
        if torch.any(~zero_level_env_mask):
            update_env_ids = env_ids[~zero_level_env_mask]
            self.position_ranges[update_env_ids] = self.initial_position_ranges[update_env_ids] # * self.current_levels[update_env_ids].unsqueeze(-1)
            self.velocity_range_list[update_env_ids] = self.initial_velocity_range_list[update_env_ids] # * self.current_levels[update_env_ids].unsqueeze(-1)
        
        # get default joint state
        joint_min_pos = asset.data.default_joint_pos[env_ids] + self.position_ranges[env_ids, 0].unsqueeze(-1)
        joint_max_pos = asset.data.default_joint_pos[env_ids] + self.position_ranges[env_ids, 1].unsqueeze(-1)
        joint_min_vel = asset.data.default_joint_vel[env_ids] + self.velocity_range_list[env_ids, 0].unsqueeze(-1)
        joint_max_vel = asset.data.default_joint_vel[env_ids] + self.velocity_range_list[env_ids, 1].unsqueeze(-1)
        
        if torch.any(zero_level_env_mask):
            # update_env_ids = env_ids[zero_level_env_mask]
            joint_min_pos[zero_level_env_mask, self.lift_joint_ids[0]] = self.lift_joint_heights[env_ids][zero_level_env_mask, 0]
            joint_min_pos[zero_level_env_mask, self.lift_joint_ids[1]] = self.lift_joint_heights[env_ids][zero_level_env_mask, 1]
            joint_max_pos[zero_level_env_mask, self.lift_joint_ids[0]] = self.lift_joint_heights[env_ids][zero_level_env_mask, 0]
            joint_max_pos[zero_level_env_mask, self.lift_joint_ids[1]] = self.lift_joint_heights[env_ids][zero_level_env_mask, 1]
        
        # clip pos to range
        joint_pos_limits = asset.data.soft_joint_pos_limits[env_ids, ...]
        joint_min_pos = torch.clamp(joint_min_pos, min=joint_pos_limits[..., 0], max=joint_pos_limits[..., 1])
        joint_max_pos = torch.clamp(joint_max_pos, min=joint_pos_limits[..., 0], max=joint_pos_limits[..., 1])
        # # clip lift joints to range
        # joint_min_pos[:, self.lift_joint_ids[0]] = torch.clamp(joint_min_pos[:, self.lift_joint_ids[0]], min=self.lift_joint_heights[:, 0])
        # joint_min_pos[:, self.lift_joint_ids[1]] = torch.clamp(joint_max_pos[:, self.lift_joint_ids[1]], min=self.lift_joint_heights[:, 1])
        # clip vel to range
        joint_vel_abs_limits = asset.data.soft_joint_vel_limits[env_ids]
        joint_min_vel = torch.clamp(joint_min_vel, min=-joint_vel_abs_limits, max=joint_vel_abs_limits)
        joint_max_vel = torch.clamp(joint_max_vel, min=-joint_vel_abs_limits, max=joint_vel_abs_limits)
        # sample these values randomly
        joint_pos = math_utils.sample_uniform(joint_min_pos, joint_max_pos, joint_min_pos.shape, env.device)
        joint_vel = math_utils.sample_uniform(joint_min_vel, joint_max_vel, joint_min_vel.shape, env.device)
        
        # # set lift joints to the given heights if less than the table height
        # joint_pos[env_ids, self.lift_joint_ids[0]] = torch.where(joint_pos[env_ids, self.lift_joint_ids[0]] < self.lift_joint_heights[env_ids, 0], self.lift_joint_heights[env_ids, 0], joint_pos[env_ids, self.lift_joint_ids[0]])
        
        
        if torch.any(zero_level_env_mask):
            # update_env_ids = env_ids[zero_level_env_mask]
            
            joint_pos[zero_level_env_mask, self.lift_joint_ids[0]] = self.lift_joint_heights[env_ids][zero_level_env_mask, 0]
            joint_pos[zero_level_env_mask, self.lift_joint_ids[1]] = self.lift_joint_heights[env_ids][zero_level_env_mask, 1]
            
        joint_pos[:, self.lift_joint_ids[0]] = torch.clamp(joint_pos[:, self.lift_joint_ids[0]], min=self.lift_joint_heights[env_ids, 0])
        joint_pos[:, self.lift_joint_ids[1]] = torch.clamp(joint_pos[:, self.lift_joint_ids[1]], min=self.lift_joint_heights[env_ids, 1])
            
        # set into the physics simulation
        asset.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)
                 


def reset_root_state_uniform_set_height(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    pose_range: dict[str, tuple[float, float]],
    set_heights: list[float],
    velocity_range: dict[str, tuple[float, float]],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Reset the asset root state to a random position and velocity uniformly within the given ranges.

    This function randomizes the root position and velocity of the asset.

    * It samples the root position from the given ranges and adds them to the default root position, before setting
      them into the physics simulation.
    * It samples the root orientation from the given ranges and sets them into the physics simulation.
    * It samples the root velocity from the given ranges and sets them into the physics simulation.

    The function takes a dictionary of pose and velocity ranges for each axis and rotation. The keys of the
    dictionary are ``x``, ``y``, ``z``, ``roll``, ``pitch``, and ``yaw``. The values are tuples of the form
    ``(min, max)``. If the dictionary does not contain a key, the position or velocity is set to zero for that axis.
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]
    # get default root state
    root_states = asset.data.default_root_state[env_ids].clone()

    # poses
    range_list = [pose_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
    ranges = torch.tensor(range_list, device=asset.device)
    rand_samples = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=asset.device)

    positions = root_states[:, 0:2] + env.scene.env_origins[env_ids, 0:2] + rand_samples[:, 0:2]
    set_heights_tensor = torch.tensor([set_heights[0]] * env.num_envs if len(set_heights) == 1 else set_heights, device=asset.device)
    # reverse the set_heights_tensor
    positions = torch.cat([positions, set_heights_tensor[env_ids].unsqueeze(1)], dim=1)
    orientations_delta = math_utils.quat_from_euler_xyz(rand_samples[:, 3], rand_samples[:, 4], rand_samples[:, 5])
    orientations = math_utils.quat_mul(root_states[:, 3:7], orientations_delta)
    # velocities
    range_list = [velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
    ranges = torch.tensor(range_list, device=asset.device)
    rand_samples = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=asset.device)

    velocities = root_states[:, 7:13] + rand_samples

    # set into the physics simulation
    asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
    asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)
    
    # update initial object position 
    masked_object_position_idx = env.observation_manager.active_terms["policy"].index("masked_object_position")
    updated_positions = positions - env.scene.env_origins[env_ids, 0:3]
    # env_ids_copy = env_ids.clone()
    env.observation_manager._group_obs_term_cfgs["policy"][masked_object_position_idx].func.reset(env_ids, updated_positions)

def reset_root_state_with_random_orientation(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    pose_range: dict[str, tuple[float, float]],
    velocity_range: dict[str, tuple[float, float]],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Reset the asset root position and velocities sampled randomly within the given ranges
    and the asset root orientation sampled randomly from the SO(3).

    This function randomizes the root position and velocity of the asset.

    * It samples the root position from the given ranges and adds them to the default root position, before setting
      them into the physics simulation.
    * It samples the root orientation uniformly from the SO(3) and sets them into the physics simulation.
    * It samples the root velocity from the given ranges and sets them into the physics simulation.

    The function takes a dictionary of position and velocity ranges for each axis and rotation:

    * :attr:`pose_range` - a dictionary of position ranges for each axis. The keys of the dictionary are ``x``,
      ``y``, and ``z``. The orientation is sampled uniformly from the SO(3).
    * :attr:`velocity_range` - a dictionary of velocity ranges for each axis and rotation. The keys of the dictionary
      are ``x``, ``y``, ``z``, ``roll``, ``pitch``, and ``yaw``.

    The values are tuples of the form ``(min, max)``. If the dictionary does not contain a particular key,
    the position is set to zero for that axis.
    """
    # extract the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]
    # get default root state
    root_states = asset.data.default_root_state[env_ids].clone()

    # poses
    range_list = [pose_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z"]]
    ranges = torch.tensor(range_list, device=asset.device)
    rand_samples = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 3), device=asset.device)

    positions = root_states[:, 0:3] + env.scene.env_origins[env_ids] + rand_samples
    orientations = math_utils.random_orientation(len(env_ids), device=asset.device)

    # velocities
    range_list = [velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
    ranges = torch.tensor(range_list, device=asset.device)
    rand_samples = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=asset.device)

    velocities = root_states[:, 7:13] + rand_samples

    # set into the physics simulation
    asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
    asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)


def reset_root_state_from_terrain(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    pose_range: dict[str, tuple[float, float]],
    velocity_range: dict[str, tuple[float, float]],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Reset the asset root state by sampling a random valid pose from the terrain.

    This function samples a random valid pose(based on flat patches) from the terrain and sets the root state
    of the asset to this position. The function also samples random velocities from the given ranges and sets them
    into the physics simulation.

    The function takes a dictionary of position and velocity ranges for each axis and rotation:

    * :attr:`pose_range` - a dictionary of pose ranges for each axis. The keys of the dictionary are ``roll``,
      ``pitch``, and ``yaw``. The position is sampled from the flat patches of the terrain.
    * :attr:`velocity_range` - a dictionary of velocity ranges for each axis and rotation. The keys of the dictionary
      are ``x``, ``y``, ``z``, ``roll``, ``pitch``, and ``yaw``.

    The values are tuples of the form ``(min, max)``. If the dictionary does not contain a particular key,
    the position is set to zero for that axis.

    Note:
        The function expects the terrain to have valid flat patches under the key "init_pos". The flat patches
        are used to sample the random pose for the robot.

    Raises:
        ValueError: If the terrain does not have valid flat patches under the key "init_pos".
    """
    # access the used quantities (to enable type-hinting)
    asset: RigidObject | Articulation = env.scene[asset_cfg.name]
    terrain: TerrainImporter = env.scene.terrain

    # obtain all flat patches corresponding to the valid poses
    valid_positions: torch.Tensor = terrain.flat_patches.get("init_pos")
    if valid_positions is None:
        raise ValueError(
            "The event term 'reset_root_state_from_terrain' requires valid flat patches under 'init_pos'."
            f" Found: {list(terrain.flat_patches.keys())}"
        )

    # sample random valid poses
    ids = torch.randint(0, valid_positions.shape[2], size=(len(env_ids),), device=env.device)
    positions = valid_positions[terrain.terrain_levels[env_ids], terrain.terrain_types[env_ids], ids]
    positions += asset.data.default_root_state[env_ids, :3]

    # sample random orientations
    range_list = [pose_range.get(key, (0.0, 0.0)) for key in ["roll", "pitch", "yaw"]]
    ranges = torch.tensor(range_list, device=asset.device)
    rand_samples = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 3), device=asset.device)

    # convert to quaternions
    orientations = math_utils.quat_from_euler_xyz(rand_samples[:, 0], rand_samples[:, 1], rand_samples[:, 2])

    # sample random velocities
    range_list = [velocity_range.get(key, (0.0, 0.0)) for key in ["x", "y", "z", "roll", "pitch", "yaw"]]
    ranges = torch.tensor(range_list, device=asset.device)
    rand_samples = math_utils.sample_uniform(ranges[:, 0], ranges[:, 1], (len(env_ids), 6), device=asset.device)

    velocities = asset.data.default_root_state[:, 7:13] + rand_samples

    # set into the physics simulation
    asset.write_root_pose_to_sim(torch.cat([positions, orientations], dim=-1), env_ids=env_ids)
    asset.write_root_velocity_to_sim(velocities, env_ids=env_ids)


def reset_joints_by_scale(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    position_range: tuple[float, float],
    velocity_range: tuple[float, float],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Reset the robot joints by scaling the default position and velocity by the given ranges.

    This function samples random values from the given ranges and scales the default joint positions and velocities
    by these values. The scaled values are then set into the physics simulation.
    """
    # extract the used quantities (to enable type-hinting)
    asset: Articulation = env.scene[asset_cfg.name]
    # get default joint state
    joint_pos = asset.data.default_joint_pos[env_ids].clone()
    joint_vel = asset.data.default_joint_vel[env_ids].clone()

    # scale these values randomly
    joint_pos *= math_utils.sample_uniform(*position_range, joint_pos.shape, joint_pos.device)
    joint_vel *= math_utils.sample_uniform(*velocity_range, joint_vel.shape, joint_vel.device)

    # clamp joint pos to limits
    joint_pos_limits = asset.data.soft_joint_pos_limits[env_ids]
    joint_pos = joint_pos.clamp_(joint_pos_limits[..., 0], joint_pos_limits[..., 1])
    # clamp joint vel to limits
    joint_vel_limits = asset.data.soft_joint_vel_limits[env_ids]
    joint_vel = joint_vel.clamp_(-joint_vel_limits, joint_vel_limits)

    # set into the physics simulation
    asset.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)


def reset_joints_by_offset(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    position_range: tuple[float, float],
    velocity_range: tuple[float, float],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("robot"),
):
    """Reset the robot joints with offsets around the default position and velocity by the given ranges.

    This function samples random values from the given ranges and biases the default joint positions and velocities
    by these values. The biased values are then set into the physics simulation.
    """
    # extract the used quantities (to enable type-hinting)
    asset: Articulation = env.scene[asset_cfg.name]

    # get default joint state
    joint_pos = asset.data.default_joint_pos[env_ids].clone()
    joint_vel = asset.data.default_joint_vel[env_ids].clone()

    # bias these values randomly
    joint_pos += math_utils.sample_uniform(*position_range, joint_pos.shape, joint_pos.device)
    joint_vel += math_utils.sample_uniform(*velocity_range, joint_vel.shape, joint_vel.device)

    # clamp joint pos to limits
    joint_pos_limits = asset.data.soft_joint_pos_limits[env_ids]
    joint_pos = joint_pos.clamp_(joint_pos_limits[..., 0], joint_pos_limits[..., 1])
    # clamp joint vel to limits
    joint_vel_limits = asset.data.soft_joint_vel_limits[env_ids]
    joint_vel = joint_vel.clamp_(-joint_vel_limits, joint_vel_limits)

    # set into the physics simulation
    asset.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)


def reset_scene_to_default(env: ManagerBasedEnv, env_ids: torch.Tensor):
    """Reset the scene to the default state specified in the scene configuration."""
    # rigid bodies
    for rigid_object in env.scene.rigid_objects.values():
        # obtain default and deal with the offset for env origins
        default_root_state = rigid_object.data.default_root_state[env_ids].clone()
        default_root_state[:, 0:3] += env.scene.env_origins[env_ids]
        # set into the physics simulation
        rigid_object.write_root_state_to_sim(default_root_state, env_ids=env_ids)
    # articulations
    for articulation_asset in env.scene.articulations.values():
        # obtain default and deal with the offset for env origins
        default_root_state = articulation_asset.data.default_root_state[env_ids].clone()
        default_root_state[:, 0:3] += env.scene.env_origins[env_ids]
        # set into the physics simulation
        articulation_asset.write_root_state_to_sim(default_root_state, env_ids=env_ids)
        # obtain default joint positions
        default_joint_pos = articulation_asset.data.default_joint_pos[env_ids].clone()
        default_joint_vel = articulation_asset.data.default_joint_vel[env_ids].clone()
        # set into the physics simulation
        articulation_asset.write_joint_state_to_sim(default_joint_pos, default_joint_vel, env_ids=env_ids)


def reset_cylinder_joints_by_position(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    position: dict[str, float],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("cylinder"),
):
    """Reset the cylinder joints by setting the joint positions to the given position.

    """
    # extract the used quantities (to enable type-hinting)
    asset: Articulation = env.scene[asset_cfg.name]
    # get default joint state
    joint_pos = asset.data.default_joint_pos[env_ids].clone()
    joint_vel = asset.data.default_joint_vel[env_ids].clone()

    reset_root_state_uniform(env, env_ids, pose_range={"x": (0.0, 0.0), "y": (0.0, 0.0), "z": (0.0, 0.0), "yaw": (0.0, 0.0)},
                velocity_range={
                    "x": (-0.0, 0.0),
                    "y": (-0.0, 0.0),
                    "z": (-0.0, 0.0),
                    "roll": (-0.0, 0.0),
                    "pitch": (-0.0, 0.0),
                    "yaw": (-0.0, 0.0),
                }, asset_cfg=asset_cfg)

    # set the joint positions to the given position
    joint_pos[:, 0] = position["x"]
    joint_pos[:, 1] = position["y"]
    joint_pos[:, 2] = position["z"]

    # set into the physics simulation
    asset.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)


def randomise_cylinder_velocities(
    env: ManagerBasedEnv,
    env_ids: torch.Tensor,
    velocity_range: tuple[float, float],
    grid_size: tuple[float, float],
    asset_cfg: SceneEntityCfg = SceneEntityCfg("cylinder"),
):
    """Randomize the velocities of the articulation by sampling random values from the given range.

    This function samples random velocities from the given range and sets them into the physics simulation.
    """
    # check if env_ids is empty
    if len(env_ids) > 0:
        # extract the used quantities (to enable type-hinting)
        asset: Articulation = env.scene[asset_cfg.name]
        # get the current velocities
        joint_vel = asset.data.joint_vel[env_ids].clone()
        # get the current positions
        joint_pos = asset.data.joint_pos[env_ids].clone()

        # check if cylinder is outside of the grid
        grid_min_x, grid_max_x = -grid_size[0]/2, grid_size[0]/2
        grid_min_y, grid_max_y = -grid_size[1]/2, grid_size[1]/2
        
        outside_x_below = (joint_pos[:, 0] < grid_min_x)
        outside_x_above = (joint_pos[:, 0] > grid_max_x)
        outside_y_below = (joint_pos[:, 1] < grid_min_y)
        outside_y_above = (joint_pos[:, 1] > grid_max_y)

        # if outside of the grid reset the joint position to inside the grid
        joint_pos[outside_x_below, 0] = grid_min_x + 0.25
        joint_pos[outside_x_above, 0] = grid_max_x - 0.25
        joint_pos[outside_y_below, 1] = grid_min_y + 0.25
        joint_pos[outside_y_above, 1] = grid_max_y - 0.25

        # sample random joint velocities
        joint_vel = math_utils.sample_uniform(*velocity_range, joint_vel.shape, device=asset.device)

        # if outside of the grid, reset the joint velocities so that the cylinder doesn't move out of the grid
        joint_vel[outside_x_below, 0] = joint_vel[outside_x_below, 0].abs()
        joint_vel[outside_x_above, 0] = -joint_vel[outside_x_above, 0].abs()
        joint_vel[outside_y_below, 1] = joint_vel[outside_y_below, 1].abs()
        joint_vel[outside_y_above, 1] = -joint_vel[outside_y_above, 1].abs()

        joint_vel[:, 2] = 0.0

        # set into the physics simulation
        asset.write_joint_state_to_sim(joint_pos, joint_vel, env_ids=env_ids)
    

"""
Internal helper functions.
"""


def _randomize_prop_by_op(
    data: torch.Tensor,
    distribution_parameters: tuple[float | torch.Tensor, float | torch.Tensor],
    dim_0_ids: torch.Tensor | None,
    dim_1_ids: torch.Tensor | slice,
    operation: Literal["add", "scale", "abs"],
    distribution: Literal["uniform", "log_uniform", "gaussian"],
) -> torch.Tensor:
    """Perform data randomization based on the given operation and distribution.

    Args:
        data: The data tensor to be randomized. Shape is (dim_0, dim_1).
        distribution_parameters: The parameters for the distribution to sample values from.
        dim_0_ids: The indices of the first dimension to randomize.
        dim_1_ids: The indices of the second dimension to randomize.
        operation: The operation to perform on the data. Options: 'add', 'scale', 'abs'.
        distribution: The distribution to sample the random values from. Options: 'uniform', 'log_uniform'.

    Returns:
        The data tensor after randomization. Shape is (dim_0, dim_1).

    Raises:
        NotImplementedError: If the operation or distribution is not supported.
    """
    # resolve shape
    # -- dim 0
    if dim_0_ids is None:
        n_dim_0 = data.shape[0]
        dim_0_ids = slice(None)
    else:
        n_dim_0 = len(dim_0_ids)
        dim_0_ids = dim_0_ids[:, None]
    # -- dim 1
    if isinstance(dim_1_ids, slice):
        n_dim_1 = data.shape[1]
    else:
        n_dim_1 = len(dim_1_ids)

    # resolve the distribution
    if distribution == "uniform":
        dist_fn = math_utils.sample_uniform
    elif distribution == "log_uniform":
        dist_fn = math_utils.sample_log_uniform
    elif distribution == "gaussian":
        dist_fn = math_utils.sample_gaussian
    else:
        raise NotImplementedError(
            f"Unknown distribution: '{distribution}' for joint properties randomization."
            " Please use 'uniform', 'log_uniform', 'gaussian'."
        )
    # perform the operation
    if operation == "add":
        data[dim_0_ids, dim_1_ids] += dist_fn(*distribution_parameters, (n_dim_0, n_dim_1), device=data.device)
    elif operation == "scale":
        data[dim_0_ids, dim_1_ids] *= dist_fn(*distribution_parameters, (n_dim_0, n_dim_1), device=data.device)
    elif operation == "abs":
        data[dim_0_ids, dim_1_ids] = dist_fn(*distribution_parameters, (n_dim_0, n_dim_1), device=data.device)
    else:
        raise NotImplementedError(
            f"Unknown operation: '{operation}' for property randomization. Please use 'add', 'scale', or 'abs'."
        )
    return data
